### ISSUE TITLE
Failed to remove message for item id

### ISSUE THREAD

**Issue by swiezaczek** [kacpi2442/am_bot#13]
Failed to remove message for item id: 80021
Traceback (most recent call last):
  File "C:\Users\ASUS ROG\Desktop\am_bot-mainkopia\s.py", line 334, in foodsi
    tg = telegram_bot_delete_message([stock['msg_id'] for stock in foodsi_in_stock if stock['id'] == item['id']][0])
  File "C:\Users\ASUS ROG\Desktop\am_bot-mainkopia\s.py", line 334, in <listcomp>
    tg = telegram_bot_delete_message([stock['msg_id'] for stock in foodsi_in_stock if stock['id'] == item['id']][0])
KeyError: 'msg_id'

----edit:
It may used old version of am_bot hence why I received this error, but SOMETIMES there is an issue with foodsi offers not being deleted when unavailable anymore, but no error is showing up

**Comment by swiezaczek** [comment]
I am closing it for now, I will reopen when have more info for you
