### ISSUE TITLE
foodsi error - missing api

### ISSUE THREAD

**Issue by garfild1994** [kacpi2442/am_bot#30]
app return this error 

Traceback (most recent call last):
  File "C:\Users\rymsz\Downloads\am_bot-main\am_bot-main\watch_script.py", line 366, in refresh
    foodsi()
  File "C:\Users\rymsz\Downloads\am_bot-main\am_bot-main\watch_script.py", line 282, in foodsi
    items += parse_foodsi_api(foodsi_api.json())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rymsz\Downloads\am_bot-main\am_bot-main\watch_script.py", line 249, in parse_foodsi_api
    for restaurant in api_result['data']:
                      ~~~~~~~~~~^^^^^^^^
KeyError: 'data'

**Comment by zajsu** [comment]
i have the same issue

**Comment by Robertnoob12** [comment]
Me too

**Comment by ruben966** [comment]
Idk how to fix it but here is how to suppress it so you can at least use the tgtg notifications without the bot spamming the error.
Add a # in front of line 366 in the watch_script.py
